import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputFile = path.join(projectRoot, "auth-runtime.js");

await build({
  entryPoints: [path.join(projectRoot, "auth-entry.js")],
  outfile: outputFile,
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["es2020"],
  minify: true,
  legalComments: "none",
  banner: {
    js: "/* Generated by npm run build:auth from auth-entry.js and npm dependencies. */",
  },
});

const bundledRuntime = await readFile(outputFile, "utf8");
await writeFile(outputFile, bundledRuntime.replace(/[ \t]+$/gm, ""));

console.log("Built reproducible Supabase auth runtime.");
